name: Python Formatting Suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check with black
      run: |
        black . --check
#    - name: Lint with flake8
#      run: |
#        flake8 . --count --statistics --show-source
    - name: Lint .md files with mdformat
      run: |
        mdformat . --check
    - name: Build PyPi Package
      run: |
        python3 -m pip install --upgrade build
        python -m build
